

spring:
  data:
    mongodb:
      uri: mongodb+srv://ajykumar284_db_user:db7CraCkuDurHsvp@cluster0.auyj2xd.mongodb.net/?appName=Cluster0



jwt:
  secret: sweetshop-secret-key
  expiration: 86400000  # 1 day in milliseconds